---
- hosts: node11
  vars:
    output_file: "/tmp/{{ ansible_hostname }}"
  tasks:
    - name: create output file on ansible control node
      file:
        path: "{{ output_file }}"
        state: touch
      tags:
        - output

    - block:
        - name: get system facts
          setup:
            filter: "*{{ item }}*"
          with_items:
            - dist
            - ip
            - kernel
            - ansible_eth
          register: system_facts

        - name: write system facts to output file
          blockinfile:
            path: "{{ output_file }}"
            block: "{{ system_facts | to_nice_json }}"
            marker: "{mark} SYSTEM FACTS"
      tags:
        - system_facts

    - name: Check for Hugepages
      shell: "{{ item }}"
      with_items:
        - cat /proc/sys/vm/nr_hugepages
        - cat /proc/meminfo | grep Huge
      register: HugePages 
    
    - name: Check for Transparent Huge Pages(THP)
      shell: "{{ item }}"
      with_items:
        - cat /sys/kernel/mm/transparent_hugepage/enabled
        - grep AnonHuge /proc/meminfo
      register: THP
      tags: THP

    - block:
        - name: Check for CPU Soft Lockup Errors
          shell: sudo egrep -i 'soft.*lock' /var/log/syslog 
          register: soft_locks
        
        - debug:
            msg: |
              CPU locks found for {{ ansible_hostname }}
              "{{ soft_locks.stdout }}"
          when: soft_locks.stdout is regex("CPU.*stuck")

    
...
